#!/usr/bin/env python3
"""
OSBB Assistant Bootstrap

Создает внутреннюю структуру библиотеки Assistant.

Запуск:

python bootstrap.py
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent


DIRECTORIES = (
    "Assistant",
    "Assistant/shared",
    "Assistant/core",
    "Assistant/git",
    "Assistant/project",
    "Assistant/commands",
    "Assistant/tools",
)


def ensure(path: Path):

    path.mkdir(parents=True, exist_ok=True)

    init = path / "__init__.py"

    if not init.exists():
        init.write_text(
            '"""Auto-generated by Assistant bootstrap."""\n',
            encoding="utf-8",
        )

    print("OK ", path.relative_to(ROOT))


def main():

    print()
    print("Assistant Bootstrap")
    print("=" * 40)

    for directory in DIRECTORIES:
        ensure(ROOT / directory)

    print()
    print("Done.")


if __name__ == "__main__":
    main()