from tkinter import *
wnd=Tk()
wnd.title("Simple window")
wnd.geometry("250x150")
wnd.resizable(False, False)
lbl=Label(wnd, text="Hello!", font=("Arial Bold",20))
lbl.place(x=40, y=30)
btn=Button(wnd, text="CLOSE", font=("Courier New Bold",13), command=wnd.destroy)
btn.place(x=40, y=100, width=170, height=30)
wnd.mainloop()
